# Generated by Django 5.2.4 on 2025-07-24 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('grocery', 'Grocery Store'), ('pharmacy', 'Pharmacy'), ('electronics', 'Electronics'), ('clothing', 'Clothing'), ('bakery', 'Bakery'), ('butchery', 'Butchery'), ('hardware', 'Hardware Store'), ('other', 'Other')], max_length=50)),
                ('business_description', models.TextField(blank=True)),
                ('tin_number', models.CharField(max_length=50, unique=True)),
                ('business_license_number', models.CharField(max_length=100)),
                ('business_address', models.TextField()),
                ('business_phone', models.CharField(max_length=15)),
                ('business_email', models.EmailField(max_length=254)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('business_license', 'Business License'), ('tin_certificate', 'TIN Certificate'), ('trade_permit', 'Trade Permit'), ('health_certificate', 'Health Certificate'), ('fire_safety', 'Fire Safety Certificate'), ('other', 'Other')], max_length=50)),
                ('document_file', models.FileField(upload_to='business_documents/')),
                ('document_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vendors.businessprofile')),
            ],
        ),
    ]
