# Generated by Django 5.2.4 on 2025-07-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
